# https://packit.dev/docs/configuration/

specfile_path: greenboot-rs.spec

files_to_sync:
  - src:
      - greenboot-rs.spec
      - .packit.yaml
      - greenboot-rs-*.tar.xz
    dest: .
  
upstream_package_name: greenboot-rs
downstream_package_name: greenboot-rs

upstream_tag_template: v{version}
copy_upstream_release_description: true
sync_changelog: true

# Use clean release string without commit hashes/branch names
release_suffix: ""

srpm_build_deps:
  - cargo

actions:
  get-current-version:
  - grep -oP '^Version:\s+\K\S+' greenboot-rs.spec
  post-upstream-clone:
  - "sed -i '/^%global forgeurl/d' greenboot-rs.spec"
  - "sed -i '/^%forgemeta/d' greenboot-rs.spec"
  - "sed -i '/^%forgeautosetup/d' greenboot-rs.spec"
  - bash -c "git config user.name 'Packit Build' || true"
  - bash -c "git config user.email 'packit@fedoraproject.org' || true"
  # Create vendor tarball here so it runs for both copr_build and propose_downstream
  - "cargo vendor vendor"
  - bash -c "tar -cJf greenboot-rs-${PACKIT_PROJECT_VERSION}-vendor-patched.tar.xz vendor"
  - bash -c "rm -rf vendor"
  - bash -c "ls -1 ./greenboot-rs-*.tar.xz"
  fix-spec-file:
  # This runs after Packit's release processing - disable debug package to prevent saypaul error
  - "sed -i '/^License:/a\\%global debug_package %{nil}' greenboot-rs.spec"

jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - centos-stream-10-aarch64
  - centos-stream-10-x86_64
  - fedora-development-aarch64
  - fedora-development
  - fedora-eln-aarch64
  - fedora-eln

- job: propose_downstream
  trigger: release
  dist_git_branches:
    - fedora-development
    - fedora-stable

- job: koji_build
  trigger: commit
  allowed_pr_authors: [all_committers]
  dist_git_branches:
    - fedora-development
    - fedora-stable

- job: bodhi_update
  trigger: commit
  allowed_builders: [all_committers]
  dist_git_branches:
    - fedora-development
    - fedora-stable

